"""create initial tables

Revision ID: 234045a590d1
Revises: 
Create Date: 2026-06-16 16:22:44.693574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234045a590d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('study_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_goals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_goals_user_id'), ['user_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['study_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_status'), ['status'], unique=False)

    op.create_table('study_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tasks_topic_id'), ['topic_id'], unique=False)

    op.create_table('review_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['study_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_task_id'), ['task_id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['study_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_task_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('review_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_schedules_task_id'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_review_date'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_id'))

    op.drop_table('review_schedules')
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_tasks_topic_id'))
        batch_op.drop_index(batch_op.f('ix_study_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_study_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_study_tasks_due_date'))

    op.drop_table('study_tasks')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_status'))
        batch_op.drop_index(batch_op.f('ix_topics_priority'))
        batch_op.drop_index(batch_op.f('ix_topics_id'))
        batch_op.drop_index(batch_op.f('ix_topics_goal_id'))

    op.drop_table('topics')
    with op.batch_alter_table('study_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_goals_status'))
        batch_op.drop_index(batch_op.f('ix_study_goals_id'))

    op.drop_table('study_goals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
